twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: ['bootstrap_5_layout.html.twig']
    globals:
        path_image_menu: '%img_directory%'

when@test:
    twig:
        strict_variables: true
